# Libretro++
FLAGS += -I$(CORE_DIR)/../../include

# Source files
SOURCES_CXX := $(wildcard \
	$(CORE_DIR)/*.cpp \
)

# Objects and Flags
OBJECTS += $(SOURCES_CXX:.cpp=.o) $(SOURCES_C:.c=.o) $(SOURCES_S:.S=.o) $(SOURCES_M:.m=.o)
LDFLAGS +=  $(fpic) $(SHARED) $(EXTRA_LDF)
WARNINGS :=
# Windows: Fix retro_common_api.h
ifeq ($(system_platform), win)
	FLAGS += -DPRId64=I64d -DPRIu64=I64u -DPRIuPTR=Iu
endif